---
name: 🐛 Bug Report
description: Reporte um problema ou bug
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do bug
      placeholder: O bot não está executando trades...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Passos detalhados para reproduzir o comportamento
      placeholder: |
        1. Execute 'python main_multibot.py'
        2. Configure bot com '...'
        3. Observe erro em '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer
      placeholder: O bot deveria executar o trade automaticamente
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que está acontecendo
      placeholder: O bot ignora o sinal e não executa nada
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      description: Onde o bug ocorre?
      options:
        - Testnet
        - Produção
        - Ambos
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Versão do Python
      description: Execute `python --version`
      placeholder: "3.9.7"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Sistema Operacional
      placeholder: "Windows 11, Ubuntu 22.04, macOS 13"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs Relevantes
      description: Cole logs do erro (REMOVA credenciais antes!)
      render: shell
      placeholder: |
        2025-12-11 10:30:45 - ERROR - Bot 1 failed: ...

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Qualquer outra informação relevante
      placeholder: O problema começou após atualizar a dependência X...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Testei em ambiente testnet
        - label: Verifiquei logs em `logs/`
        - label: Li a documentação relevante
        - label: Procurei por issues similares
        - label: Removi credenciais dos logs