---
name: ✨ Feature Request
description: Sugira uma nova funcionalidade
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma melhoria! Por favor, descreva sua ideia.

  - type: textarea
    id: problem
    attributes:
      label: Problema/Motivação
      description: Descreva o problema que esta feature resolveria
      placeholder: Atualmente é difícil visualizar P&L por criptomoeda...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Como você imagina que esta feature funcionaria?
      placeholder: Um novo gráfico no dashboard que mostra P&L agrupado por símbolo...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Outras abordagens que você considerou?
      placeholder: Poderia ser um relatório em CSV exportável...

  - type: dropdown
    id: component
    attributes:
      label: Componente Afetado
      description: Qual parte do sistema seria modificada?
      multiple: true
      options:
        - Bot/Trading Engine
        - AI Orchestrator
        - Dashboard Streamlit
        - Frontend React
        - API Backend
        - Configuração
        - Documentação
        - Deploy/AWS
        - Outro

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade Sugerida
      options:
        - Baixa (nice to have)
        - Média (melhoria útil)
        - Alta (feature importante)
        - Crítica (necessário urgente)

  - type: textarea
    id: examples
    attributes:
      label: Exemplos de Uso
      description: Como seria usar esta feature?
      placeholder: |
        ```python
        # Exemplo de código ou screenshot
        bot.configure(new_feature=True)
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribuição
      options:
        - label: Estou disposto(a) a implementar esta feature
        - label: Estou disposto(a) a testar esta feature
        - label: Estou disposto(a) a documentar esta feature