name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Trading Strategy
        - Dashboard/UI
        - Risk Management
        - Performance/Optimization
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking me from using the bot)
        - High (significantly improves workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: Technical details, API changes, etc.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: This feature would benefit other users, not just me
          required: true